export enum ContentType {
    JSON = 'application/json',
    HTML = 'text/html',
    PLAIN_TEXT = 'text/plain',
    XML = 'application/xml',
    FORM_URLENCODED = 'application/x-www-form-urlencoded',
    MULTIPART_FORM_DATA = 'multipart/form-data',
    CSS = 'text/css',
    JAVASCRIPT = 'application/javascript',
    JPEG = 'image/jpeg',
    PNG = 'image/png',
    GIF = 'image/gif',
    SVG = 'image/svg+xml',
    WEBP = 'image/webp',
    WAV = 'audio/wav',
    MP3 = 'audio/mpeg',
    MP4 = 'video/mp4',
    OGG_AUDIO = 'audio/ogg',
    OGG_VIDEO = 'video/ogg',
    OCTET_STREAM = 'application/octet-stream',
    PDF = 'application/pdf',
    ZIP = 'application/zip',
    GZIP = 'application/gzip',
}
